import {test} from 'node:test';
import assert from 'node:assert/strict';
import {handleApi} from '../../netlify/functions/api';
import {AppError,type LibraryBook} from '../../packages/contracts/src/index';
import type {AuthServices} from '../../packages/infrastructure/src/auth';
const actor='98000000-0000-4000-8000-000000000001',bid='98000000-0000-4000-8000-000000000002',cid='98000000-0000-4000-8000-000000000003';
const book:LibraryBook={id:bid,name:'Sample',author:'',genres:[],label:'Chương',chapterCount:1,hasCover:false,progress:null,progressIndex:null,version:1};
function fixture(text='safe text'){let hidden=false;let calls:string[]=[];const services:AuthServices={async verify(){return {id:actor,email:'sample@gmail.com',email_confirmed_at:'2026-10-08',app_metadata:{provider:'google'}};},async rpc(name,args){calls.push(name);assert.equal(args.actor,actor);if(name==='app_me')return {id:actor,name:'Reader',permissions:['read']};if(name==='app_reader_book'){if(hidden)throw new AppError('NOT_FOUND',404,'Hidden');return book;}if(name==='app_reader_chapters')return {book,chapters:[{id:cid,index:0,order:1,displayNumber:'1',title:'Sample',part:'',volume:'',cacheTag:'tag'}],total:1,offset:0};if(name==='app_reader_resource')return {fileId:'registered',bookName:'Sample',sourceType:'FILE',cacheKey:'key',cached:{text,title:'Safe title'}};throw Error('Unexpected RPC');}};const request=()=>handleApi(new Request(`https://app.test/api/books/${bid}/cluster?start=0`,{headers:{Authorization:'Bearer verified'}}),{},undefined,services);return {request,calls,services,hide:()=>hidden=true};}
test('cluster content byte budget rejects oversized cached payload',async()=>{const f=fixture('é'.repeat(1_000_001));const response=await f.request();assert.equal(response.status,200);const item=(await response.json()).items[0];assert(item.error);assert.equal(item.text,undefined);});
test('publication rechecked after all cached content before cluster response',async()=>{const f=fixture();f.hide();assert.equal((await f.request()).status,404);assert(f.calls.includes('app_reader_resource'));assert(f.calls.includes('app_reader_book'));});
test('permission denial aborts whole cluster rather than returning private partial data',async()=>{const f=fixture();const original=f.services.rpc.bind(f.services);f.services.rpc=(name,args)=>name==='app_reader_resource'?Promise.reject(new AppError('FORBIDDEN',403,'Revoked')):original(name,args);const response=await f.request();assert.equal(response.status,403);assert(!JSON.stringify(await response.json()).includes('safe text'));});
