import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {localPool} from '../../packages/infrastructure/src/database';
import {migrate} from './migrate';
import {handleApi} from '../../netlify/functions/api';
import {AppError,LibraryPage,ChapterPage} from '../../packages/contracts/src/index';
import type {AuthServices} from '../../packages/infrastructure/src/auth';
import {fixture} from '../../tests/phase-3/drive-fixture';
const original=process.env.DATABASE_URL||'postgresql://postgres:local-only-password@127.0.0.1:55432/bookdownloader',admin=localPool(original),name='book_reader_test_'+randomUUID().replaceAll('-',''),url=new URL(original);url.pathname='/'+name;
const uid=(n:number)=>`91000000-0000-4000-8000-${String(n).padStart(12,'0')}`,bid=(n:number)=>`92000000-0000-4000-8000-${String(n).padStart(12,'0')}`,cid=(n:number)=>`93000000-0000-4000-8000-${String(n).padStart(12,'0')}`,gid=(n:number)=>`94000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
let pool:ReturnType<typeof localPool>|undefined,passed=0;
async function check(label:string,fn:()=>Promise<void>){await fn();passed++;console.log('PASS '+label);}
try{
 await admin.query('create database '+name);process.env.DATABASE_URL=url.href;await migrate();pool=localPool(url.href);const db=await pool.connect();
 try{
  for(let n=1;n<=2;n++)await db.query("insert into auth.users(id,email,email_confirmed_at,raw_app_meta_data) values($1,'synthetic@gmail.com',now(),'{\"provider\":\"google\"}')",[uid(n)]);
  for(let n=1;n<=27;n++)await db.query("insert into public.books(id,name,normalized_name,author,source_type,visibility,folder_id) values($1,$2,$3,$4,'FILE',$5,$6)",[bid(n),n===1?'Đường về cổ tích':'Truyện '+String(n).padStart(3,'0'),'truyen '+n,n===1?'Tác giả mẫu':'Author '+n,n===27?'hidden':'published',n===1?'book':'folder-'+n]);
  await db.query("insert into public.chapter_groups(id,book_id,kind,name,order_key) values($1,$2,'PART','Phần một',0)",[gid(1),bid(1)]);await db.query("insert into public.chapter_groups(id,book_id,parent_id,kind,name,order_key) values($1,$2,$3,'VOLUME','Quyển một',1)",[gid(2),bid(1),gid(1)]);
  const f=fixture();
  for(let n=1;n<=9;n++){const file=await f.drive.putText('book','Chương '+n+'.txt','Đường về cổ tích\n\nChương '+n+': Mẫu\n\nNội dung tự viết cho kiểm thử chương '+n+'.',1);await db.query("insert into public.chapters(id,book_id,group_id,legacy_order,order_key,display_number,title,status,file_id) values($1,$2,$3,$4,$4,$5,$6,'DONE',$7)",[cid(n),bid(1),n<3?gid(2):null,n===1?-.5:n,n===1?'*':n===2?'1-2':String(n),n===1?'Lời tựa':'Chương '+n+': Mẫu',file]);await db.query("insert into public.drive_resources(file_id,book_id,chapter_id,owner_subject,kind,metadata_version,sync_status) values($1,$2,$3,'synthetic-owner','CHAPTER',1,'synced')",[file,bid(1),cid(n)]);}
  const origin='https://app.test';
  function service(n:number):AuthServices{return {async verify(){return {id:uid(n),email:'synthetic@gmail.com',email_confirmed_at:'2026-10-08',app_metadata:{provider:'google'}};},async rpc(rpc,args){const params:Record<string,unknown[]>={app_me:[args.actor],app_library:[args.actor,args.query,args.sort_by,args.page_offset],app_reader_book:[args.actor,args.target_book],app_reader_chapters:[args.actor,args.target_book,args.page_offset,args.page_limit],app_reader_resource:[args.actor,args.target_book,args.target_chapter],app_reader_cache:[args.actor,args.target_book,args.target_chapter,args.expected_key,args.new_value],app_preferences:[args.actor,args.new_value],app_progress:[args.actor,args.target_book,args.new_value]};if(!params[rpc])throw Error('Unexpected RPC');const placeholders=params[rpc].map((_,i)=>'$'+(i+1)).join(',');try{return (await db.query(`select public.${rpc}(${placeholders}) as value`,params[rpc])).rows[0].value;}catch(error:any){throw new AppError(error.code==='42501'?'FORBIDDEN':error.code==='P0002'?'NOT_FOUND':error.code==='40001'?'CONFLICT':'FAILED',error.code==='42501'?403:error.code==='P0002'?404:error.code==='40001'?409:500,'Rejected');}}};}
  const api=(path:string,n=1,method='GET',body?:unknown)=>handleApi(new Request(origin+'/api'+path,{method,headers:{Authorization:'Bearer synthetic',Origin:origin,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)}),{APP_ORIGINS:origin},undefined,service(n),f.drive);
  await check('library paginates 24 and hides unpublished books',async()=>{const first=LibraryPage.parse(await (await api('/books')).json());assert.equal(first.total,26);assert.equal(first.books.length,24);assert(!first.books.some(b=>b.id===bid(27)));const last=LibraryPage.parse(await (await api('/books?offset=24')).json());assert.equal(last.books.length,2);assert.equal(new Set([...first.books,...last.books].map(b=>b.id)).size,26);});
  await check('accentless search matches name/author and no internal metadata leaks',async()=>{for(const q of ['DUONG VE','tac gia mau']){const response=await api('/books?q='+encodeURIComponent(q));const data=LibraryPage.parse(await response.json());assert.equal(data.total,1);assert.equal(data.books[0].id,bid(1));assert.equal(data.books[0].progress,null);assert.equal(data.books[0].progressIndex,null);assert(!JSON.stringify(data).includes('folderId'));assert(!JSON.stringify(data).includes('fileId'));}});
  await check('library order is deterministic and author sort works',async()=>{const data=LibraryPage.parse(await (await api('/books?sort=author')).json());const expected=[...data.books].sort((a,b)=>a.author.localeCompare(b.author,'en'));assert.deepEqual(data.books.map(b=>b.id),expected.map(b=>b.id));});
  await check('invalid offset/sort/limit rejected before SQL business IO',async()=>{for(const path of ['/books?offset=-1','/books?sort=evil',`/books/${bid(1)}/chapters?limit=201`,`/books/${bid(1)}/cluster?start=1`])assert.equal((await api(path)).status,400);});
  await check('chapter page retains groups/preface/range/order and opaque cache tag',async()=>{const page=ChapterPage.parse(await (await api(`/books/${bid(1)}/chapters?limit=2`)).json());assert.equal(page.total,9);assert.equal(page.chapters[0].order,-.5);assert.equal(page.chapters[0].displayNumber,'*');assert.equal(page.chapters[1].displayNumber,'1-2');assert.equal(page.chapters[0].part,'Phần một');assert.equal(page.chapters[0].volume,'Quyển một');assert.match(page.chapters[0].cacheTag,/^[a-f0-9]{32}$/);const last=ChapterPage.parse(await (await api(`/books/${bid(1)}/chapters?offset=8`)).json());assert.equal(last.chapters[0].index,8);});
  await check('cluster returns exactly five and content works without worker',async()=>{const response=await api(`/books/${bid(1)}/cluster?start=0`);assert.equal(response.status,200);const data=await response.json();assert.equal(data.items.length,5);assert.match(data.items[0].text,/kiểm thử chương 1/);assert(!JSON.stringify(data).includes('created-'));});
  await check('cluster final partial window and missing-file error state',async()=>{await db.query("update public.drive_resources set sync_status='error' where chapter_id=$1",[cid(9)]);const response=await api(`/books/${bid(1)}/cluster?start=5`);assert.equal(response.status,200);const data=await response.json();assert.equal(data.items.length,4);assert(data.items[3].error);await db.query("update public.drive_resources set sync_status='synced' where chapter_id=$1",[cid(9)]);});
  await check('empty and hidden/deleted book states',async()=>{const empty=await api(`/books/${bid(2)}/chapters`);assert.equal(empty.status,200);assert.deepEqual((await empty.json()).chapters,[]);assert.equal((await api(`/books/${bid(27)}`)).status,404);await db.query('update public.books set deleted_at=now() where id=$1',[bid(2)]);assert.equal((await api(`/books/${bid(2)}`)).status,404);});
  await check('per-user progress/card and page preferences persist independently',async()=>{const value={chapterId:cid(2),ratio:.4,scrollPosition:50,expectedRevision:0};assert.equal((await api('/me/progress/'+bid(1),1,'PUT',value)).status,200);const one=await (await api('/books/'+bid(1))).json(),two=await (await api('/books/'+bid(1),2)).json();assert.equal(one.progress.chapterId,cid(2));assert.equal(one.progressIndex,1);assert.equal(two.progress,null);const prefs={font:'Tinos',fontSize:22,theme:'night',blueFilter:.15,mode:'chapter',view:'page'};assert.deepEqual(await (await api('/me/preferences',1,'PUT',prefs)).json(),prefs);assert.equal(await (await api('/me/preferences',2)).json(),null);});
  await check('two devices cannot overwrite same revision and read latest server position',async()=>{const value={chapterId:cid(3),ratio:.5,scrollPosition:60,expectedRevision:1};assert.equal((await api('/me/progress/'+bid(1),1,'PUT',value)).status,200);assert.equal((await api('/me/progress/'+bid(1),1,'PUT',{...value,chapterId:cid(4)})).status,409);const latest=await (await api('/me/progress/'+bid(1))).json();assert.equal(latest.chapterId,cid(3));assert.equal(latest.revision,2);});
  await check('revocation and publication changes deny cached cluster',async()=>{await db.query("update public.books set visibility='hidden' where id=$1",[bid(1)]);assert.equal((await api('/books/'+bid(1)+'/cluster?start=0')).status,404);await db.query("update public.books set visibility='published' where id=$1",[bid(1)]);await db.query('delete from public.user_permissions where user_id=$1',[uid(1)]);assert.equal((await api('/books')).status,403);assert.equal((await api('/books/'+bid(1)+'/cluster?start=0')).status,403);});
  await check('browser role cannot spoof reader actor RPCs',async()=>{await db.query('set role authenticated');for(const sql of ['select public.app_library($1)','select public.app_reader_book($1,$2)','select public.app_reader_chapters($1,$2)'])await assert.rejects(db.query(sql,sql.includes('$2')?[uid(2),bid(1)]:[uid(2)]),{code:'42501'});await db.query('reset role');});
  console.log(`Reader SQL/API: ${passed} passed; isolated database removed.`);
 }finally{db.release();}
}finally{process.env.DATABASE_URL=original;await pool?.end();await admin.query('drop database if exists '+name);await admin.end();}
