import {useEffect,useRef,useState} from 'react';
import {LibraryPage,type LibraryBook} from '../../../../packages/contracts/src/index';
import {persist,stored,userKey,type Call} from './model';
import {Reader} from './Reader';
function Cover({book,asset}:{book:LibraryBook;asset:(path:string,init?:RequestInit)=>Promise<Blob>}){
 const [url,setUrl]=useState('');const wrapper=useRef<HTMLDivElement>(null);useEffect(()=>{if(!book.hasCover)return;const controller=new AbortController();let active=true,object='';const load=()=>{void asset('/books/'+book.id+'/cover',{signal:controller.signal}).then(blob=>{if(active){object=URL.createObjectURL(blob);setUrl(object);}}).catch(()=>{});};const observer=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)){observer.disconnect();load();}},{rootMargin:'100px'});if(wrapper.current)observer.observe(wrapper.current);return()=>{active=false;observer.disconnect();controller.abort();if(object)URL.revokeObjectURL(object);};},[book.id,book.hasCover,book.version,asset]);
 return <div ref={wrapper}>{url?<img loading="lazy" className="book-cover" src={url} alt={'Ảnh bìa '+book.name}/>:<div className="book-cover fallback" aria-label="Bìa chữ">{book.name}</div>}</div>;
}
export function Library({user,call,asset,notify}:{user:string;call:Call;asset:(path:string,init?:RequestInit)=>Promise<Blob>;notify:(text:string)=>void}){
 const [query,setQuery]=useState(''),[sort,setSort]=useState('name'),[offset,setOffset]=useState(0),[view,setView]=useState(()=>stored(userKey(user,'library-view'),'grid')),[page,setPage]=useState<ReturnType<typeof LibraryPage.parse>|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState<LibraryBook|null>(null),[refresh,setRefresh]=useState(0);
 useEffect(()=>{const controller=new AbortController();setBusy(true);setError('');setPage(null);const timer=setTimeout(()=>{void call('/books?'+new URLSearchParams({q:query,sort,offset:String(offset)}),{signal:controller.signal}).then(data=>{if(!controller.signal.aborted)setPage(LibraryPage.parse(data));}).catch(e=>{if(!controller.signal.aborted)setError(e.message||'Không tải được thư viện');}).finally(()=>{if(!controller.signal.aborted)setBusy(false);});},query?250:0);return()=>{clearTimeout(timer);controller.abort();};},[query,sort,offset,refresh,call]);
 if(selected)return <Reader key={selected.id} user={user} initialBook={selected} call={call} notify={notify} back={()=>{setSelected(null);setRefresh(n=>n+1);}}/>;
 return <div className="library"><h1>Đọc truyện</h1><div className="library-tools"><label>Tìm truyện<input value={query} placeholder="Tên, tác giả, thể loại" onChange={e=>{setQuery(e.target.value);setOffset(0);}}/></label><label>Sắp xếp<select value={sort} onChange={e=>{setSort(e.target.value);setOffset(0);}}><option value="name">Tên truyện</option><option value="author">Tác giả</option><option value="updated">Mới cập nhật</option><option value="progress">Đọc gần đây</option></select></label><button aria-pressed={view==='grid'} onClick={()=>{setView('grid');persist(userKey(user,'library-view'),'grid');}}>Dạng lưới</button><button aria-pressed={view==='table'} onClick={()=>{setView('table');persist(userKey(user,'library-view'),'table');}}>Dạng bảng</button></div>
 {busy&&<p role="status">Đang tải thư viện…</p>}{error&&<div role="alert">{error}<button onClick={()=>setRefresh(n=>n+1)}>Thử lại</button></div>}{page&&!busy&&<><p>{page.total} truyện đã xuất bản</p>{!page.books.length?<p>Không tìm thấy truyện đã xuất bản.</p>:view==='grid'?<div className="book-grid">{page.books.map(book=><article key={book.id} className="book-card"><Cover book={book} asset={asset}/><h2>{book.name}</h2><p>{book.author||'Chưa rõ tác giả'}</p><p>{book.genres.join(', ')||'Chưa phân loại'} · {book.chapterCount} {book.label.toLowerCase()}</p>{book.progress&&<p>Đang đọc chương thứ {(book.progressIndex??0)+1} · {Math.round(book.progress.ratio*100)}%</p>}<button onClick={()=>setSelected(book)}>{book.progress?'Đọc tiếp':'Đọc truyện'}: {book.name}</button></article>)}</div>:<div className="library-table"><table><thead><tr><th>Tên truyện</th><th>Tác giả</th><th>Thể loại</th><th>Số chương</th><th>Tiến độ</th><th>Đọc</th></tr></thead><tbody>{page.books.map(book=><tr key={book.id}><td>{book.name}</td><td>{book.author||'Chưa rõ'}</td><td>{book.genres.join(', ')}</td><td>{book.chapterCount}</td><td>{book.progress?Math.round(book.progress.ratio*100)+'%':'Chưa đọc'}</td><td><button onClick={()=>setSelected(book)}>Mở {book.name}</button></td></tr>)}</tbody></table></div>}<div className="pagination"><button disabled={!offset} onClick={()=>setOffset(n=>Math.max(0,n-24))}>Trang trước</button><span>Trang {Math.floor(offset/24)+1}</span><button disabled={offset+24>=page.total} onClick={()=>setOffset(n=>n+24)}>Trang sau</button></div></>}
 </div>;
}
